version: "3"
services:
    consent:
        image: mshare/consent
        build: ./services/consent
        volumes:
            - ./services/consent:/app
        entrypoint: CompileDaemon --build="go build -o /consent" --command=/consent
        ports:
            - 8180:8080
        depends_on:
            - "mongo"
        environment:
            MONGO_URL: "mongodb://mongo:27017"
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: consent
    healthcare-provider:
        image: mshare/healthcare-provider
        build: ./services/healthcare-provider
        volumes:
            - ./services/healthcare-provider:/app
        entrypoint: CompileDaemon --build="go build -o /healthcare-provider" --command=/healthcare-provider
        ports:
            - 8280:8080
        depends_on:
            - "mongo"
        environment:
            MONGO_URL: "mongodb://mongo:27017"
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: healthcare-provider
            JWT_SECRET: development
    medication-record:
        image: mshare/medication-record
        build: ./services/medication-record
        volumes:
            - ./services/medication-record:/app
        entrypoint: CompileDaemon --build="go build -o /medication-record" --command=/medication-record
        ports:
            - 8380:8080
        depends_on:
            - "fhir"
        environment:
            FHIR_URL: fhir
            PRODUCTION: "true"
            GCP_SERVICE_ACCOUNT_PRIVATE_KEY: "{\"type\": \"service_account\",\"project_id\": \"dcs-medication-sharing\",\"private_key_id\": \"1f5d8595a6d7eb5b9239776571ff38ac8341d9bc\",\"private_key\": \"-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmIyHnIIz0+z0g\\nvr3S9jTC6koIgr6H/70QbPC8qekg1StqPSUydvgCUPP9FeQ84NBuR4HlclTPH32K\\nQn6hgae77zx7rhuIjb6LeZvOnGsEIkxsU74SSnM2SC48sIF+YXwEvXlzf2Ebixj/\\nfgJ9oUM5uj5EyzEHfwYiCk0SRsBvEXEkmiKeyp2foMe8OQD/m/27VRW3hdDb6/+U\\nYFAp8z9+Ow1n3fYUTpHArW+HHhF/nbg4Z3jGvGN5hZ+WbT0O4E3Fl+KzY606826C\\njOmMibEUAhyU+KCZF3oZoG4f9Sl1l9n4hDRkXsSCUIrAbZ/9QfuF5k3bnCinA0PA\\nts6uDJPhAgMBAAECggEAF3VY/Wdrd9D80+GS8JWKpCYMT5DUgeQCqG3VfTI5pITt\\nBSp+lNZXFQ6ksOz1JgJxc8zdgs4muvs9kPbsJfZmfoMchXMzWI/5In0Imr8b3kDQ\\njTAy46bHB1hgTPn4QuXVat7tJfmLtuWoYTUD+YS6dw186t5M/Tu6nDZbpRO/6r6v\\nl37Mnn7nwDBy+K0IC3X3vjmuW9/IGCKmnmF40IKcv0bVIQ7kwO6Uf9djH26A/LZ4\\nPrLT6mJOGCACW+rpAfLxgpbX6UANuL22HhDJkzGldK/BExZBm0seZbcTnBgxUphi\\nmgL38CrVUFfzH2YhEu7F549i99TwUfMnjXEpCybz1QKBgQDd5Kgjkj2i3RRIuRgp\\n7+AGLDMI1k5kYt+iFWG4vOho0wQRxuAyspBQRFrqT4HXzRlwu+1BmG5QkVltVudS\\n8em19T7Wxn9EnRk2+ohbgLTaRk3BL248ticBjs2QfFLiXsGYmqG1O5LtXKjl8Pg0\\nRQ6PilHFNkcO2e3zRjl7aFrP/QKBgQC/rIR598frM/eyyirFvmS6ekFe/kYtOi5S\\nv1/Fd46ORiP1lI4ymQc+U7+ml62ynp7IcIDryE6SifHTIDvrym19NOfA8fZ0HeuC\\n2NlcHopQVMqLKeoeIRFGkGmikF04+rJJPXlRXS9rTl6hnMb/QmHVXHzYZXxE+0NK\\n6k2sdC1+tQKBgBlI8Q/8niFs597RmLtOpkyNxNMA+LXfvnQN07DldeZcBV6xNuMQ\\nDfnXkDSbEsSwjnGWOJb887UimvomqP1+q48cfyiiPeZnsHPfYKJsrC8jS8Dz0rAA\\nYbl/uFT6lcdN3Omy1TJ9s2Rw5p4tM1thcyNQM7kxUi+TDdZm7i3t2ktRAoGAdriT\\nwbxA/yVMKljgj2TznTF2ZjFXJFJiOOzClFwOV3+IbGdcgGiavPdAwR43/2gSb5KH\\nuAN0730z5RKVKuJSWPg5CCCXB6s0ofJRB6b/AuzSG8qVcZ4Hxk5Sr9d9dnqJjaXf\\nDA+M/IkpQi8Kbzcdw/sqdRq/EzcSokdoXwYC2/UCgYEAo42M4uFPZj1qBcUG5G7v\\nffaA9ZE3nMIXoqBYEcCi2Dfvextz8jX0rYsYt1P35PR5tH7eFIYfVfmY3r0yepYF\\nf87Ft8E2Fr6OEKwaG5hEHzBIAsbn61/rrd5v8UqY/qCpzaEls+9yL/IqmWJvPbNJ\\nu5IC5aLz8pHr0PFCnwQNegs=\\n-----END PRIVATE KEY-----\\n\",\"client_email\": \"medication-record-account@dcs-medication-sharing.iam.gserviceaccount.com\",\"client_id\": \"103939269771276923209\",\"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\"token_uri\": \"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/medication-record-account%40dcs-medication-sharing.iam.gserviceaccount.com\"}"
    standardization:
        image: mshare/standardization
        build: ./services/standardization
        volumes:
            - ./services/standardization:/app
        entrypoint: CompileDaemon --build="go build -o /standardization" --command=/standardization
        ports:
            - 8480:8080
    mongo:
        image: mongo:4.4
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    react-frontend:
        image: mshare/react-frontend
        build: ./services/react-frontend
        volumes:
            - /app/node_modules
            - ./services/react-frontend:/app
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_PRODUCTION=false
        command: npm start
    fhir:
        image: "hapiproject/hapi:latest"
        ports:
            - "8085:8080"
