version: "3"
services:
    consent:
        image: mshare/consent
        build: ./services/consent
        volumes:
            - ./services/consent:/app
        ports:
            - 8081:8080
    healthcare-provider:
        image: mshare/healthcare-provider
        build: ./services/healthcare-provider
        volumes:
            - ./services/healthcare-provider:/app
        ports:
            - 8082:8080
    medication-record:
        image: mshare/medication-record
        build: ./services/medication-record
        volumes:
            - ./services/medication-record:/app
        ports:
            - 8083:8080
    standardization:
        image: mshare/standardization
        build: ./services/standardization
        volumes:
            - ./services/standardization:/app
        ports:
            - 8084:8080
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
