version: "3"
services:
    consent:
        image: mshare/consent
        build: ./services/consent
        volumes:
            - ./services/consent:/app
        entrypoint: CompileDaemon --command=/consent
        ports:
            - 8180:8080
        depends_on:
            - "mongo"
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: consent
            MONGO_DB_HOST: mongo
            MONGO_PORT: 27017
    healthcare-provider:
        image: mshare/healthcare-provider
        build: ./services/healthcare-provider
        volumes:
            - ./services/healthcare-provider:/app
        entrypoint: CompileDaemon --command=/healthcare-provider
        ports:
            - 8280:8080
        depends_on:
            - "mongo"
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: healthcare-provider
            MONGO_DB_HOST: mongo
            MONGO_PORT: 27017
    medication-record:
        image: mshare/medication-record
        build: ./services/medication-record
        volumes:
            - ./services/medication-record:/app
        entrypoint: CompileDaemon --command=/medication-record
        ports:
            - 8380:8080
        environment:
            FHIR_URL: fhir
    standardization:
        image: mshare/standardization
        build: ./services/standardization
        volumes:
            - ./services/standardization:/app
        entrypoint: CompileDaemon --command=/standardization
        ports:
            - 8480:8080
        depends_on:
            - "mongo"
        environment:
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: standardization
            MONGO_DB_HOST: mongo
            MONGO_PORT: 27017
    mongo:
        image: mongo:4.4
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    react-frontend:
        image: mshare/react-frontend
        build: ./services/react-frontend
        volumes:
            - /app/node_modules
            - ./services/react-frontend:/app
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
    fhir:
        image: "hapiproject/hapi:latest"
        ports:
            - "8085:8080"
