version: "3"
services:
    consent:
        image: mshare/consent
        build: ./services/consent
        volumes:
            - ./services/consent:/app
        ports:
            - 8081:8080
        depends_on:
            - "mongo"
        environment: 
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: consent
            MONGO_PORT: 27017
    healthcare-provider:
        image: mshare/healthcare-provider
        build: ./services/healthcare-provider
        volumes:
            - ./services/healthcare-provider:/app
        ports:
            - 8082:8080
        depends_on:
            - "mongo"
        environment: 
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: healthcare-provider
            MONGO_PORT: 27017
    medication-record:
        image: mshare/medication-record
        build: ./services/medication-record
        volumes:
            - ./services/medication-record:/app
        ports:
            - 8083:8080
    standardization:
        image: mshare/standardization
        build: ./services/standardization
        volumes:
            - ./services/standardization:/app
        ports:
            - 8084:8080
        depends_on:
            - "mongo"
        environment: 
            MONGO_USERNAME: root
            MONGO_PASSWORD: example
            MONGO_DB_NAME: standardization
            MONGO_PORT: 27017
    mongo:
        image: mongo:4.4
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
